builders:
  reflectable:
    target: ":reflectable"
    import: "package:reflectable/reflectable_builder.dart"
    builder_factories: ["reflectableBuilder"]
    build_extensions: { ".dart": ["_proxy.dart"] }
    auto_apply: root_package
    runs_before:
      - reflectable|organize_builder
    build_to: source
    defaults:
      generate_for:
        exclude:
          - lib/**.dart
          - example/**/lib/src/**.dart
        include:
          # - benchmark/**.dart
          # - bin/**.dart
          - example/**/lib/**.dart
          # - lib/main.dart
          # - test/**.dart
          # - tool/**.dart
          # - web/**.dart
  organize_builder:
    target: ":reflectable"
    import: "package:reflectable/organize_builder.dart"
    builder_factories: ["organizeBuilder"]
    build_extensions: { "_proxy.dart": ["_mirror.dart"] }
    auto_apply: root_package
    build_to: source
    defaults:
      generate_for:
        exclude:
        include:
          - example/**_proxy.dart
