builders:
  reflectable:
    target: ":reflectable"
    import: "package:reflectable/reflectable_builder.dart"
    builder_factories: ["reflectableBuilder"]
    build_extensions: { ".dart": ["_proxy.dart"] }
    auto_apply: root_package
    build_to: source
    defaults:
      generate_for:
        exclude:
          - lib/**.dart
        include:
          - benchmark/**.dart
          - bin/**.dart
          - example/**/lib/**.dart
          - lib/main.dart
          - test/**.dart
          - tool/**.dart
          - web/**.dart
